# Generated by Django 4.0.4 on 2022-05-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoApp', '0002_userkeys_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserKeys',
        ),
    ]
